### ISSUE TITLE
"AssertionError: undefined == true"

### ISSUE THREAD

**Issue by miparnisari** [evshiron/nwjs-builder#54]
I get this error when trying to package my app:

```bash
λ nwb nwbuild -v 0.18.2-sdk -o "windows" -p win32 --side-by-side .
{ version: 'v0.18.2',
  flavor: 'sdk',
  targets: [ [ 'win', 'x86' ] ],
  path: '.' }
0: Read package.json
1: Prepare build directory at windows\app-win-ia32
2: Copy binary from C:\Users\miparnisari\.nwjs-builder\caches\binary-nwjs-sdk-v0.18.2-win-ia32
3: Edit Windows executable

C:\Users\miparnisari\AppData\Roaming\npm\node_modules\nwjs-builder\node_modules\regenerator-runtime\runtime.js:522
        throw exception;
        ^
 AssertionError: undefined == true
    at Object._callee2$ (C:\Users\miparnisari\AppData\Roaming\npm\node_modules\nwjs-builder\lib\build\win32.js:210:25)
    at tryCatch (C:\Users\miparnisari\AppData\Roaming\npm\node_modules\nwjs-builder\node_modules\regenerator-runtime\runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\miparnisari\AppData\Roaming\npm\node_modules\nwjs-builder\node_modules\regenerator-runtime\runtime.js:336:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\miparnisari\AppData\Roaming\npm\node_modules\nwjs-builder\node_modules\regenerator-runtime\runtime.js:95:21)
    at Immediate._onImmediate (C:\Users\miparnisari\AppData\Roaming\npm\node_modules\nwjs-builder\node_modules\node-async-flow\lib\index.js:15:22)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by evshiron** [comment]
Sorry for the misleading message. These `assert` was for convenience and I have done a refining using `if` instead of `assert` in 702902d, and will be published when the next version releases.
